### ISSUE TITLE
Failure on install

### ISSUE THREAD

**Issue by pandabrand** [TypistTech/vagrant-trellis-cert#42]
I have tried install this plugin but I get this error:
`Unable to resolve dependency: user requested 'vagrant-bindfs (= 1.0.3)'`
My bind-fs is 1.0.9

**Comment by TangRufus** [comment]
This vagrant plugin doesn’t require vagrant-bindfs directly. It’s a Trellis/ vagrant requirement. 

Try update to latest Trellis and vagrant, then reinstall all vagrant plugins. 

See: https://github.com/hashicorp/vagrant/issues/8054

**Comment by TangRufus** [comment]
And note that this plugin only works on macOS. pull requests are welcomed.

**Comment by pandabrand** [comment]
Thanks, running `vagrant plugin expunge --reinstall` and then manually installing the plugins it complained about for me:
```
vagrant-vbguest
vagrant-hostmanager
vagrant-bindfs
```

fixed this for me.
