### ISSUE TITLE
Does it still work on latest Trellis?

### ISSUE THREAD

**Issue by TangRufus** [TypistTech/vagrant-trellis-cert#52]
Trellis no longer use `.dev`.
Does this work on `.test`?

https://github.com/TypistTech/vagrant-trellis-cert/blob/b4978bcf57058d39bf3c8da681d739fa31e17e43/lib/vagrant_plugins/trellis_cert/config.rb#L72-L74

**Comment by raulillana** [comment]
It does in the v1.2.0 (which also uses .test).

**Comment by TangRufus** [comment]
This is one of those things that written too long ago and I forgot what it does.
Seems that line just a glorified string for error messages
