### ISSUE TITLE
Plugin fails to install on latest version of Vagrant (2.2.8)

### ISSUE THREAD

**Issue by ttamnedlog** [TypistTech/vagrant-trellis-cert#57]
When trying to install the vagrant-trellis-cert plugin on the latest version of Vagrant **(2.2.8),** I receive this error:
```shell
vagrant-trellis-cert requires Ruby version ~> 2.4.2. The current ruby version is 2.6.6.146.
```
Downgrading to my previous version of Vagrant **(2.2.6)** allows me to install the plugin without issue. 2.2.7 may have also worked, but I didn't try it.

**Additional details**
- **OS:** macOS Catalina 10.15.4
- **System-installed Ruby:** 2.6.3p62 (2019-04-16 revision 67580) although it looks like Vagrant has and uses its own Ruby
- **Brew-installed Ruby:** 2.7.1p83 (2020-03-31 revision a0c7c23c9c) but this isn't even in my PATH, so I don't believe it is being used for this. I tried adding it to PATH, but no difference.

**Comment by 2crstn** [comment]
I can confirm this. Tried to use RVM, but that version (2.4.9) is not recognized.

**Comment by TangRufus** [comment]
Thanks for reporting.
This issue has been resolved in https://github.com/TypistTech/vagrant-trellis-cert/pull/58 
Please try `$ vagrant plugin install vagrant-trellis-cert` again.

Let me know if you encounter any issues.
